RF_n_estimators: 25
RF_max_depth: 10
RFR_n_estimators: 50
RFR_max_depth: 20
SVM_random_state: 0
SVM_max_iterations: 10000000
SVM_multi_class: crammer_singer
LR_random_state: 0
DTC_random_state: 0
RNN_window_size: 2
RNN_n : 10
RNN_epochs : 100
RNN_learning_rate : 0.01
MLP_solver : lbfgs
MLP_random_state : 1
MLP_layers : 5
MLP_neurons : 2
MLP_alpha : 0.0001
RNR_radius: 1.0
