rf_estimators: 25
rf_max_depth: 10
r_n_estimators: 50
r_max_depth: 20
s_random_state: 0
s_max_iterations: 10000000
s_multi_class: crammer_singer
lr_random_state: 0
dtc_random_state: 0
rnn_window_size: 2
rnn_n : 10
rnn_epochs : 100
rnn_learning_rate : 0.01
mlp_solver : lbfgs
mlp_random_state : 1
mlp_layers : 5
mlp_neurons : 2
mlp_alpha : 0.0001
rnr_radius: 1.0
kmeans_bins : 3
kneighbors_classifiernn : 3
perceptron_class_weight: balanced
rfc_max_features : sqrt
logisticregression_solver : newton-cg
KNeighborsClassifier_algorithm : ball_tree
